####### AUTH REGISTER
POST https://react-mern-production.up.railway.app/api/auth/new
Content-Type: application/json

{
  "name": "Sebastian",
  "email": "sebas@gmail.com",
  "password": "123456" 
}

####### AUTH LOGIN 
POST https://react-mern-production.up.railway.app/api/auth/
Content-Type: application/json

{
  "name": "Sebas",
  "email": "sebas@gmail.com",
  "password": "123456"
}

################################
GET https://react-mern-production.up.railway.app/api/auth/renew
Content-Type: application/json
Accept: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MTM2MTY2LCJleHAiOjE3MjUxNDMzNjZ9.SZZANoyv-8ays4ehDLNIdPo_eu9AUeBZ1YsDNKBudcE

####### GET EVENTS
GET https://react-mern-production.up.railway.app/api/events
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzkyMTA1LCJleHAiOjE3MjUzOTkzMDV9.DKF6QmkUMG-nQfyjqYLLHFvt-r3H644cjd6Qxmpnpfg

####### CREATE EVENT
POST https://react-mern-production.up.railway.app/api/events/create/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzkyMTA1LCJleHAiOjE3MjUzOTkzMDV9.DKF6QmkUMG-nQfyjqYLLHFvt-r3H644cjd6Qxmpnpfg

{
  "title": "New Event23",
  "start": 1,
  "end": 100000,
  "notes": "Comprar el pan23"
}

####### UPDATE EVENT
PUT https://react-mern-production.up.railway.app/api/events/66d7652f43603b9782935f84/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzkyMTA1LCJleHAiOjE3MjUzOTkzMDV9.DKF6QmkUMG-nQfyjqYLLHFvt-r3H644cjd6Qxmpnpfg

{
  "title": "Event updateded",
  "start": 1,
  "end": 100000,
  "notes": "Comprar el updatedded"
}

####### DELETE EVENT
DELETE https://react-mern-production.up.railway.app/api/events/66d7652f43603b9782935f84/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzkyMTA1LCJleHAiOjE3MjUzOTkzMDV9.DKF6QmkUMG-nQfyjqYLLHFvt-r3H644cjd6Qxmpnpfg
