####### AUTH REGISTER
POST http://localhost:4001/api/auth/new
Content-Type: application/json

{
  "name": "Sebastian",
  "email": "sebas@gmail.com",
  "password": "123456" 
}

####### AUTH LOGIN 
POST http://localhost:4001/api/auth/
Content-Type: application/json

{
  "name": "Sebas",
  "email": "sebas@gmail.com",
  "password": "123456"
}

################################
GET http://localhost:4001/api/auth/renew
Content-Type: application/json
Accept: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MTM2MTY2LCJleHAiOjE3MjUxNDMzNjZ9.SZZANoyv-8ays4ehDLNIdPo_eu9AUeBZ1YsDNKBudcE

####### GET EVENTS
GET http://localhost:4001/api/events
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzA0NjYwLCJleHAiOjE3MjUzMTE4NjB9.SQLQBIay-AMFDwLsOS_JVQjLSYJ9zmYGmTGS0hg04r4

####### CREATE EVENT
POST http://localhost:4001/api/events/create/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzA0NjYwLCJleHAiOjE3MjUzMTE4NjB9.SQLQBIay-AMFDwLsOS_JVQjLSYJ9zmYGmTGS0hg04r4

{
  "title": "New Event2",
  "start": 1,
  "end": 100000,
  "notes": "Comprar el pan2"
}

####### UPDATE EVENT
PUT http://localhost:4001/api/events/66d6153f0167e52e6fd0192a/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzA0NjYwLCJleHAiOjE3MjUzMTE4NjB9.SQLQBIay-AMFDwLsOS_JVQjLSYJ9zmYGmTGS0hg04r4

{
  "title": "Event updateded",
  "start": 1,
  "end": 100000,
  "notes": "Comprar el updatedded"
}

####### DELETE EVENT
DELETE http://localhost:4001/api/events/66d6153f0167e52e6fd0192a/
Content-Type: application/json
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NmQzNTA3ZWE4ZDQ3NTM4MzUxNzlhZjciLCJuYW1lIjoiU2ViYXN0aWFuIiwiaWF0IjoxNzI1MzA0NjYwLCJleHAiOjE3MjUzMTE4NjB9.SQLQBIay-AMFDwLsOS_JVQjLSYJ9zmYGmTGS0hg04r4
